### ISSUE TITLE
NuGet package installation adds binding redirect for FSharp.Core to version 4.3.0.0

### ISSUE THREAD

**Issue by vasily-kirichenko** [jack-pappas/ExtCore#11]
What's worse, it _replaces_ previous redirect with it's own:

before:

``` xml
<dependentAssembly>
    <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
</dependentAssembly>
```

after:

``` xml
<dependentAssembly>
    <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0" />
</dependentAssembly>
```

**Comment by jack-pappas** [comment]
@vasily-kirichenko Is this still an issue for you, or can I close this? If you are still seeing this issue -- is it occurring with any other packages, or only with ExtCore?

I stumbled across Microsoft/visualfsharp#283 today -- perhaps that is related to this?

**Comment by jack-pappas** [comment]
This seems to have been a VS / VFT bug -- if you think this is still something that needs to be addressed in ExtCore, please let me know and I'll re-open the issue.
