### ISSUE TITLE
Add AsyncStatefulChoiceBuilder

### ISSUE THREAD

**Issue by vasily-kirichenko** [jack-pappas/ExtCore#13]
Analogy as there's non-async pair

```fsharp
type ProtectedStateFunc<'State, 'T, 'Error> =  'State -> Choice<'T * 'State, 'Error>
type StatefulChoiceFunc<'State, 'T, 'Error> =  'State -> Choice<'T, 'Error> * 'State
```

it would be great to have async one

```fsharp
type AsyncProtectedStateFunc<'State, 'T, 'Error> =  'State -> Async<Choice<'T * 'State, 'Error>>
type AsyncStatefulChoiceFunc<'State, 'T, 'Error> =  'State -> Async<Choice<'T, 'Error> * 'State>> //missing
```

**Comment by jack-pappas** [comment]
@vasily-kirichenko This feature is in the most recent ExtCore package (0.8.45). I did some basic testing and it seems to work as expected; if you're going to depend on it for production use, please double-check that it does work correctly (and consider contributing some test cases for it, if you have the time).
