### ISSUE TITLE
AsyncChoiceBuilder x.TryFinally / x.Using issue

### ISSUE THREAD

**Issue by pavelhritonenko** [jack-pappas/ExtCore#14]
in asyncChoice computation IDisposable.Dispose called after first bind instead of calling on computation finish

    open System

    let mutable disposed = false
    
    [<SetUp>]
    let setup() = disposed <- false
    
    [<TearDown>]
    let teardown() =
        printfn "Should be disposed. Checking..."
        Assert.IsTrue(disposed)
    
    type Disposable() = 
        interface IDisposable with
            member x.Dispose() = 
                printfn "disposing!"
                disposed <- true
    
    let createAsyncChoiceDisposable() = async { return Choice1Of2(new Disposable()) }
    
    let waitAsyncChoice() = 
        asyncChoice { 
            printfn "waiting"
        }

    let shouldNotBeDisposed() =
        printfn "Should not be disposed. Checking..."
        Assert.IsFalse(disposed)

    // asyncChoice wrong behavior
    
    [<Test>]
    let usingAsyncChoice() : unit = 
        asyncChoice { 
            use! d = createAsyncChoiceDisposable()
            shouldNotBeDisposed()
            let! a = waitAsyncChoice()
            shouldNotBeDisposed()
        }
        |> Async.RunSynchronously
        |> Choice.get
        |> ignore

    // async - expected behavior

    let createAsyncDisposable() = async { return (new Disposable()) }
    
    let waitAsync() = 
        async { 
            printfn "waiting"
        }

    [<Test>]
    let usingAsync() : unit = 
        async { 
            use! d = createAsyncDisposable()
            shouldNotBeDisposed()
            do! waitAsync()
            shouldNotBeDisposed()
        }
        |> Async.RunSynchronously
        |> ignore

I think this problem in TryFinally implementation because target disposed after first bind in case of using try/finally explicit

**Comment by jack-pappas** [comment]
Pavel, this should be fixed now. I'll release a new version of the ExtCore NuGet package later today with the fixes I made for this bug.
