### ISSUE TITLE
`error` custom operator from `ChoiceBuilder` is not visible even in F# 3.1 projects

### ISSUE THREAD

**Issue by vasily-kirichenko** [jack-pappas/ExtCore#19]
![image](https://cloud.githubusercontent.com/assets/873919/7022231/45909d28-dd32-11e4-9c03-126f9969345d.png)

It seems `FX_ATLEAST_FSHARP_3_0` is not actually defined here https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/Control.fs#L790-L795

**Comment by jack-pappas** [comment]
@vasily-kirichenko Thanks for pointing this out. Leaving this out was an oversight, since ExtCore has been targeting F# 3.0 (``FSharp.Core 4.3.0.0``) for a while now. I've removed the ``#if/#else`` so the operator will be available in the next release.
