### ISSUE TITLE
Provided a nuget package for any mobile compatible profile 7/78/259 would be great.

### ISSUE THREAD

**Issue by 7sharp9** [jack-pappas/ExtCore#24]

**Comment by jack-pappas** [comment]
Good idea. I actually did the bulk of the work for this a while back (like 2 years ago) to get the code compiling under the same PCL profiles that ``FSharp.Core`` targets. I just need to fix up the build script (which I just fixed and committed) and fix up the NuGet packaging. I'll try to do that within the next couple of days and get a new version out.

**Comment by jack-pappas** [comment]
I built and published a new version of the ExtCore package (0.8.46) which includes builds for mobile profiles. I don't have much experience with PCL assemblies -- would you mind giving the new version a try to see if it has what you need (and works as you expect)?

**Comment by 7sharp9** [comment]
I will, thanks Jack!

**Comment by jack-pappas** [comment]
Dave, any luck with the new package version? Just wondering if I can close out this issue.

**Comment by 7sharp9** [comment]
Yep, sorry forgot to report back.  As far as I can tell everything's
working for mobile with pcl 7.  Thanks!
