### ISSUE TITLE
net45 tests fail

### ISSUE THREAD

**Issue by wallymathieu** [jack-pappas/ExtCore#35]
Could perhaps be due to https://github.com/nunit/nunit/issues/2518

**Comment by jindraivanek** [comment]
What is failing for you? Travis build is OK, I tried tests locally (Windows) and it is also OK.

**Comment by wallymathieu** [comment]
Try removing everything except net45 in targetframeworks for the tests and run the tests on windows. It's failing on appveyor.

**Comment by jindraivanek** [comment]
Still no failing test. Looking at appveyor log https://ci.appveyor.com/project/jack-pappas/extcore/build/0.0.47, tests succeeds, but after that it returns error code.

**Comment by wallymathieu** [comment]
Weird. Could the build error be due to the build of  `C:\projects\extcore\ExtCore.Tests\bin\Debug\netstandard1.6\ExtCore.Tests.dll`, as that should be netcoreapp and not netstandard?

**Comment by wallymathieu** [comment]
I tried to build it here: https://github.com/wallymathieu/ExtCore/tree/appveyor_trial
But that could perhaps be related to some other type of failure

**Comment by wallymathieu** [comment]
Thanks for the help and patience @jindraivanek ! 😄
